import { PaginationStyle } from "./style"


export const Pagination = () => {
    return (
        <>
            <PaginationStyle>
                A
            </PaginationStyle>
            <PaginationStyle>
                B
            </PaginationStyle>
            <PaginationStyle>
                C
            </PaginationStyle>
            <PaginationStyle>
                D
            </PaginationStyle>
            <PaginationStyle>
                E
            </PaginationStyle>
            <PaginationStyle>
                F
            </PaginationStyle>
            <PaginationStyle>
                G
            </PaginationStyle>
            <PaginationStyle>
                H
            </PaginationStyle>
            <PaginationStyle>
                I
            </PaginationStyle>
            <PaginationStyle>
                J
            </PaginationStyle>
            <PaginationStyle>
                K
            </PaginationStyle>
            <PaginationStyle>
                L
            </PaginationStyle>
            <PaginationStyle>
                M
            </PaginationStyle>
            <PaginationStyle>
                N
            </PaginationStyle>
            <PaginationStyle>
                O
            </PaginationStyle>
            <PaginationStyle>
                P
            </PaginationStyle>
            <PaginationStyle>
                Q
            </PaginationStyle>
            <PaginationStyle>
                R
            </PaginationStyle>
            <PaginationStyle>
                S
            </PaginationStyle>
            <PaginationStyle>
                T
            </PaginationStyle>
            <PaginationStyle>
                U
            </PaginationStyle>
            <PaginationStyle>
                V
            </PaginationStyle>
            <PaginationStyle>
                W
            </PaginationStyle>
            <PaginationStyle>
                X
            </PaginationStyle>
            <PaginationStyle>
                Y
            </PaginationStyle>
            <PaginationStyle>
                Z
            </PaginationStyle>
        </>
    )
}